### ISSUE TITLE
Custom limit filter

### ISSUE THREAD

**Issue by jwiel86** [tombenner/reports_kit#18]
Is there a way to do a custom limit filter?

For example:

We want to have the following checkboxes:  Top 5 Hospitals and Bottom 5 Hospitals.

The legend holds the "Hospitals", the x-axis is by month, the y-axis is % Adherence.

When the user clicks the "Top 5 Hospitals", the graph should display the top 5 hospitals.

.yml file
```
measure:
  key: event_log
  name: Percent Adherence to ACOG Guidelines (% correct steps)
  aggregation: percent_correct_steps
filters:
- top_5
- bottom_5
- session_date_time
- sites
- key: adherence_report
  criteria:
    value: true
dimensions:
- key: session_date_time
  granularity: month
- key: hospital
chart:
  type: line
  datasets:
    fill: false
  options:
    scales:
      yAxes:
      - ticks:
          min: 0
          max: 100
          stepSize: 20
    legend:
        position: right
```
model
```
def self.top_5
  order('avg(st_log_item_arguments.value) DESC').limit(5)
end

def self.bottom_5
  order('avg(st_log_item_arguments.value) ASC').limit(5)
end

include ReportsKit::Model
reports_kit do 
    filter :top_5, :boolean, conditions: ->(relation) { relation.top_5 }
    filter :bottom_5, :boolean, conditions: ->(relation) { relation.bottom_5 }
  end
end
```

Are we abusing the checkboxes here?  Should we be going about it in another way?

Thank you!
