### ISSUE TITLE
[Need help] Datetime Filter issue

### ISSUE THREAD

**Issue by kirantpatil** [tombenner/reports_kit#23]
Hi,

I created series as below without any issue. 

But once I add the Datetime filter(ie. last 8 lines in the below code ) it started to show reloading icon only. 

Please help me to find what is the issue.

Please find the below code 
```
series:
- measure:
    key: incident
    name: Open
  filters:
  - key: status
    criteria:
      operator: equals
      value: open
  dimensions:
  - created_at
- measure:
    key: incident
    name: Close
  filters:
  - key: status
    criteria:
      operator: equals
      value: close
  dimensions:
  - created_at
- measure: incident
filters:
- key: created_at
  criteria:
    operator: between
    value: -3M - now
dimensions:
- created_at
```

Thanks.

**Comment by kirantpatil** [comment]
I modified the above code in view to add date_range and now it is showing controller error as below.

## Controller error
ArgumentError in Users#index
A filter with key 'created_at' is not configured in this report

## code

```
<div class="col-sm-6">
       <%= render_report 'series_multiple' do |report| %>
          <%= report.form do |f| %>
       <div class="pull-right"></div>
      <%= f.date_range :created_at %>
      <% end %>
      <% end %>
    </div>
```

**Comment by kirantpatil** [comment]
I resolved it by adding created_at to filter as below.
```

series:
- measure:
    key: incident
    name: Open
  filters:
  - key: status
    criteria:
      operator: equals
      value: open
  - created_at
  dimensions:
  - created_at
- measure:
    key: incident
    name: Close
  filters:
  - key: status
    criteria:
      operator: equals
      value: close
  - created_at
  dimensions:
  - created_at

```
