### ISSUE TITLE
Error when using data method

### ISSUE THREAD

**Issue by ijfrederick** [tombenner/reports_kit#31]
I have created a data_method that generates a hash of the data I want to report. I am getting a NoMethodError (undefined method `[]' for nil:NilClass): when I render the report.  

About your application's environment
Rails version             5.0.2
Ruby version              2.4.2-p198 (x86_64-linux)
RubyGems version          2.6.13
Rack version              2.0.4

Seems like a simple problem and I know I am missing something in my setup but I am new and rely heavily on tutorials.  Please help.

**Comment by ijfrederick** [comment]
Resolved with version 0.6.0

**Comment by rahulpattanshetty** [comment]
@ijfrederick now u able to get charts using data_methods

**Comment by ijfrederick** [comment]
@rahulpattanshetty yes, I am able to do so using the latest version of the gem.

**Comment by rahulpattanshetty** [comment]
I am also trying to get the chart using data_method but getting the same error when I render the report

## versions
```
rails - 5.1.6
ruby - 2.4.3
reports_kit - 0.5.0

```
$cat app/services/my_data_methods.rb
```
class MyDataMethods
  def self.posts_by_author
    Post.joins(:author).group('authors.name').order('authors.name').count
  end
end
```
$cat app/config/reports_kit/reports/data_methods.yml
```
data_method: MyDataMethods.posts_by_author
chart:
  options:
    legend:
      display: false
    scales:
      xAxes:
      - scaleLabel:
          display: true
          labelString: Posts
      yAxes:
      - scaleLabel:
          display: true
          labelString: Author
```

$cat app/views/posts/index.html.erb
`<%=render_report 'data_methods'%>`

### server logs

```
Started GET "/reports_kit/reports.json?report_params%5Bkey%5D=data_methods&properties=%7B%22ui_filters%22%3A%7B%7D%7D" for 127.0.0.1 at 2018-04-12 10:16:03 +0530
Processing by ReportsKit::ReportsController#index as JSON
  Parameters: {"report_params"=>{"key"=>"data_methods"}, "properties"=>"{\"ui_filters\":{}}"}
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)

NoMethodError (undefined method `[]' for nil:NilClass):

```
