### ISSUE TITLE
instead of showing author name in dimensions it is showing #<Author,0x000564563447a0>

### ISSUE THREAD

**Issue by rahulpattanshetty** [tombenner/reports_kit#36]
$cat app/views/posts/index.html.erb
`<%= render_report 'custom_filters'%>`

$ cat config/reports_kit/reports/custom_filters.yml
```
measure:
  key: post
  name: Published Posts
filters:
- key: is_published
criteria:
  value: true
dimensions:
- author
```
In dimensions author name is not displayed in the graph. I need to display the author name in x-axis it is showing some reference number of the object i think.

### screenshot
![reportskit](https://user-images.githubusercontent.com/31472174/38480741-dfa82eee-3be4-11e8-9a8d-7c9d32c8bd91.png)
