### ISSUE TITLE
Monthly reports

### ISSUE THREAD

**Issue by inem** [tombenner/reports_kit#57]
(Just to make sure) Am I right that reports_kit can't generate monthly reports?

**Comment by tombenner** [comment]
If by monthly reports, you mean grouping by month on the x-axis (similar to [this](https://www.reportskit.co/examples/dimension_datetime), but grouped by month), then ReportsKit does indeed support that. You can do this by adding `granularity: month` to the datetime dimension, like this:
```yaml
measure: post
dimensions:
- key: created_at
  granularity: month
```
