### ISSUE TITLE
[FAQ] Operator types Documentation

### ISSUE THREAD

**Issue by kirantpatil** [tombenner/reports_kit#9]
Hi,

From example, I could see only "sum" operator from https://www.reportskit.co/examples/table_with_aggregations as below. Are there any other operators types like avg, count and so on ?

```
report_options:
  aggregations:
  - from: columns
    operator: sum
    label: Total
  - from: rows
    operator: sum
    label: Total
```
